<?php

declare(strict_types=1);

namespace M2Oidc\OAuth\Model;

use Magento\Framework\ObjectManagerInterface;

/**
 * Factory class for M2oidcOauthClientApps model.
 *
 * In a production Magento installation this class is auto-generated by the DI
 * framework.  This hand-written version exists so that:
 *  - PHPUnit can create mocks of it in standalone tests (no Magento required)
 *  - Static-analysis tools (PHPStan/Psalm) can resolve the type without stubs
 *
 * The real generated factory has exactly the same public API.
 */
class M2oidcOauthClientAppsFactory
{
    /** @var ObjectManagerInterface */
    private readonly ObjectManagerInterface $objectManager;

    /**
     * @param ObjectManagerInterface $objectManager
     */
    public function __construct(ObjectManagerInterface $objectManager)
    {
        $this->objectManager = $objectManager;
    }

    /**
     * Create a new M2oidcOauthClientApps instance.
     *
     * @param  array<string,mixed> $data
     */
    public function create(array $data = []): M2oidcOauthClientApps
    {
        return $this->objectManager->create(M2oidcOauthClientApps::class, $data);
    }
}
