<?php
use MiniOrange\OAuth\Helper\OAuthConstants;

// Initialisiere alle Variablen
$oauthsettings = $this->getExtensionPageUrl('oauthsettings');
$signinsettings = $this->getExtensionPageUrl('signinsettings');
$attrsettings = $this->getExtensionPageUrl('attrsettings');
$activeTab = $this->getCurrentActiveTab();
?>
<div style="padding: 0 1%;">
    <div class="topnav" id="myTopnav">
        <a class="nav-tab <?php echo $block->escapeHtmlAttr($activeTab == 'oauthsettings' ? 'active' : ''); ?>" href="<?php echo $block->escapeUrl($oauthsettings); ?>">OAuth Settings</a>
        <a class="nav-tab <?php echo $block->escapeHtmlAttr($activeTab == 'signinsettings' ? 'active' : ''); ?>" href="<?php echo $block->escapeUrl($signinsettings); ?>">Sign In Settings</a>
        <a class="nav-tab <?php echo $block->escapeHtmlAttr($activeTab == 'attrsettings' ? 'active' : ''); ?>" href="<?php echo $block->escapeUrl($attrsettings); ?>">Attribute Mapping</a>
    </div>
</div>
