<?php
use MiniOrange\OAuth\Helper\OAuthConstants;

// Initialisiere alle Variablen
$oauthsettings = $block->getExtensionPageUrl('oauthsettings');
$signinsettings = $block->getExtensionPageUrl('signinsettings');
$attrsettings = $block->getExtensionPageUrl('attrsettings');
$activeTab = $block->getCurrentActiveTab();
?>
<div style="padding: 0 1%;">
    <div class="topnav" id="myTopnav">
        <a class="nav-tab <?= $escaper->escapeHtmlAttr(
            $activeTab == 'oauthsettings' ? 'active' : ''
        ); ?>" href="<?= $escaper->escapeUrl($oauthsettings); ?>">
            OAuth Settings
        </a>
        <a class="nav-tab <?= $escaper->escapeHtmlAttr(
            $activeTab == 'signinsettings' ? 'active' : ''
        ); ?>" href="<?= $escaper->escapeUrl($signinsettings); ?>">
            Sign In Settings
        </a>
        <a class="nav-tab <?= $escaper->escapeHtmlAttr(
            $activeTab == 'attrsettings' ? 'active' : ''
        ); ?>" href="<?= $escaper->escapeUrl($attrsettings); ?>">
            Attribute Mapping
        </a>
    </div>
</div>
