<!-- 
    This template file is for the oauth Attribute/Role Mapping settings.
    File acts as a view file for our attribute / role mapping page.
-->

<?php
    //Attribute mapping
    // initialize all values required to be shown on the page
    $roles = $block->getAllRoles();
    $groups = $block->getAllGroups();

    $isEnabled = $block->isEnabled();
    $disabled = !$isEnabled ? "disabled" : "";
    $oauth_am_username = $block->getUserNameMapping();
    $oauth_am_email = $block->getUserEmailMapping();
    $oauth_am_first_name = $block->getFirstNameMapping();
    $oauth_am_last_name = $block->getLastNameMapping();
    $oauth_am_group_name = $block->getGroupMapping();

    $oauth_am_account_matcher = $block->getAccountMatcher();

    $emailSelected = $oauth_am_account_matcher == 'email' ? 'selected="selected"' : "";
    $usernameSelected = $oauth_am_account_matcher == 'username' ? 'selected="selected"' : "";

    $oauth_am_dont_allow_unlisted_user_role = $block->getDisallowUnlistedUserRole();
    $mo_oauth_dont_create_user_if_role_not_mapped = $block->getDisallowUserCreationIfRoleNotMapped();

    $admin_roles_configured = $block->getRolesMapped();
    $customer_roles_configured = $block->getGroupsMapped();

    $default_role = $block->getDefaultRole();
    $premiumlink = $block->getExtensionPageUrl('upgrade');

echo '
<div class="row">
<div class="col-sm-7 page_margin" >
    <div class="page" id="attrmapping">
        <div class="mooauth_table_layout">
            <form name="f" method="post" action="">
             <input name="form_key" type="hidden" value="'. $block->escapeHtmlAttr($block->getFormKey()) .'" />
                <input type="hidden" name="option" value="saveAttrSettings">
                 <h3>Role Mapping (Optional)</h3><hr>  
                 
                <table>
                        <tr>
                        <td colspan="2">
                            <div class="mo_note">
                                <span class="btn-link" >What is Role Mapping? <span style="color:red">&nbsp &nbsp &nbsp &nbsp &nbsp &nbsp *</span> <span style="color:black; font-weight:normal" > (Available in the <a href="<?php echo $this->escapeUrl($premiumlink); ?>" class="premium btn-link">premium</a> version)</span></span>
                                <div hidden class="show_info">
                                <ol>
                                <br>
                                <li>Magento uses a concept of Roles, designed to give the site owner the ability to control 
                                        what users can and cannot do within the site.</li>
                                <li>Role mapping helps you to assign specific roles to users of a certain group in your IdP.</li>
                                <li>While auto registering, the users are assigned roles based on the group they are mapped to.</li>
                            </ol>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr><td colspan="2"><b>NOTE: </b> Group will be assigned only to non-admin users (user that do NOT have Administrator 
                        privileges). You will have to manually change the group of Adminis  trator users.</td></tr>
                    <tr><td colspan="2"><input type="checkbox" id="dont_create_user_if_role_not_mapped" 
                        name="mo_oauth_dont_create_user_if_role_not_mapped" value="checked" ;
                        ' . ($mo_oauth_dont_create_user_if_role_not_mapped ? 'checked' : '') . ' 
                                       ' . $block->escapeHtmlAttr($disabled) . ' 
                         >&nbsp;&nbsp;Do not auto create users if roles are not 
                        mapped here.</td></tr>';

echo '  
                    <tr style="border-bottom: 1px solid #c1bdbd;">
                    <tr><td></td></tr>
                    <tr> 
                        <td><strong>Default Group :</strong></td>   
                        <td>    
                                <select id="saml_am_default_group" <?php echo htmlspecialchars($disabled); ?> disabled name="saml_am_default_group">
                                      style="width:150px;" >';
foreach ($groups as $group) {
    $selected = $default_role == $group['label'] ? 'selected' : '';
    echo '<option id="mo2f_roles" ' . $block->escapeHtml($selected) . 
     ' name="' . $block->escapeHtml($group['label']) . 
     '" value="' . $block->escapeHtml($group['label']) . '">' .
     $block->escapeHtml($group['label']) . '</option>';
}
echo '                           </select>   
                            <i>Select the default group to assign to  Frontend Users.</i> 
                        </td>   
                    </tr>';

if (empty($customer_roles_configured)) {
    $customer_fields = [];
} else {
    $customer_fields = [];
}
foreach ($groups as $group) {
    $role_value = $group['value'];
    $role_name = $group['label'];
    $value = isset($customer_fields[$role_value]) ? 
        $customer_fields[$role_value] : "";
        echo '<tr><td><b>' . $block->escapeHtml($role_name) . '</b></td><td><input type="text" name="oauth_am_group_attr_values_' . 
        $block->escapeHtml($role_value) . '" value="' . $block->escapeHtml($value) . '" placeholder="Semi-colon(;) separated Group/Role value for ' . 
        $block->escapeHtml($role_name) . '" style="width: 400px;" ' . $block->escapeHtml($disabled) . ' disabled></td></tr>';
}

echo '
<tr  style="border-bottom: 1px solid #c1bdbd;">
<td> </td>
<tr><td></td></tr>  
<tr>
                        <td><strong>Default Role:</strong></td>
                        <td>
                                <select id="oauth_am_default_role" <?php echo $disabled; ?> disabled name="oauth_am_default_role"
                                      style="width:150px;" >';

foreach ($roles as $role) {
    $selected = $default_role == $role['label'] ? 'selected' : '';
    echo '<option id="mo2f_roles" ' . $block->escapeHtmlAttr($selected) . ' 
    name="' . $block->escapeHtmlAttr($role['label']) . '">' . 
    $block->escapeHtmlAttr($role['label']) . '</option>';
}

echo '                           </select>
                            <i>Select the default role to assign to Backend Users.</i>
                        </td>
                    </tr>';

foreach ($roles as $role) {
    $role_value = $role['value'];
    $role_name = $role['label'];

    if (empty($admin_roles_configured)) {
        $admin_roles = [];
        $value = isset($admin_roles[$role_value]) ? $admin_roles[$role_value] : "";
        
    } else {
        $admin_roles = $admin_roles_configured;

        $value = isset($admin_roles[$role_value]) ? $admin_roles[$role_value] : "";
    }

    echo '<tr>
        <td><b>' . $block->escapeHtml($role_name) .':</b></td>
        <td>
            <input type="text"
                   name="oauth_am_admin_attr_values_'. $block->escapeHtmlAttr($role_value) .'"
                   value="'. $block->escapeHtmlAttr($value) .'"
                   placeholder="'. $block->escapeHtmlAttr("Semi-colon(;) separated Role value for " . $role_name) .'"
                   style="width: 400px;" '. $block->escapeHtmlAttr($disabled) .' disabled>
        </td>
      </tr>';
}

echo '               <tr>
                        <td>&nbsp;</td>
                        <td><br ><input type="submit" class="btn-round" style="width:100px;" name="submit" value="Save"' .$block->escapeHtmlAttr($disabled) .'disabled > &nbsp; 
                        <br ><br >
                        </td>
                    </tr>
                </table>
            </form>
        </div>
    </div>';
?>
