<!--
    This template file is for the Sign In settings.
    File acts as a view file for our Sign In settings.
-->
<?php
    // initialize all values
    $customerLink = $this->showCustomerLink() ?'checked':'';
    $adminLink = $this->showAdminLink() ?'checked':'';
    $autoCreateAdmin = $this->autoCreateAdmin() ?'checked':'';
    $autoCreateCustomer = $this->autoCreateCustomer() ?'checked':'';
    $isOAuthConfigured = $this->isOAuthConfigured() && $this->isEnabled();
    $disabled  = $isOAuthConfigured ? "" : 'disabled title="Disabled. Configure your Service Provider" ';
    $logoutUrl = $this->getAdminLogoutUrl();
    $premiumlink = $this->getExtensionPageUrl('upgrade');
    $enabledebuglog = $this->isDebugLogEnable() ? 'checked':'';
echo '
<div class="row">
<div class="col-sm-7 page_margin" > 
   <div class="page" id="samlsettings">
      <div class="mosp_table_layout">
         <h3>LOGIN / LOGOUT OPTIONS </h3>
         <hr>

     </div>
         <form id="signInSettings" method="post" action="">
            <input name="form_key" type="hidden" value="'. $block->escapeHtmlAttr($block->getFormKey()).'" />
            <input type="hidden" name="option" value="saveSingInSettings" >
            <table>
            <tr>
                            <td ><strong style="margin-right:50px">Post-Logout URL:</strong>
                           <input type="text" name="mo_oauth_logout_redirect_url" value="" disabled />
                           <br>
                           </td>
                    </tr>
               <tr>
                  <td>
                    
                     <h4><b>Show Link on Default Login Page :</b></h4>
                     <div style="margin-left:17px;margin-top:2%;">
                     <input type="checkbox" name="mo_oauth_show_customer_link" id="mo_oauth_show_customer_link" 
                        ' . $this->escapeHtmlAttr($customerLink) . '  value="true">  Show the Login Link on the default customer login page. 
                        <br><br>
                        <input type="checkbox" name="mo_oauth_show_admin_link" id="mo_oauth_show_admin_link" 
                           ' . $this->escapeHtmlAttr($adminLink) . ' value="true"> Show the Login Link on the default admin login page.
                  </td>      
               </tr>
               <tr><td>
               <lable ><strong>User Auto Create Settings </strong></lable>
               <div style="margin-left:17px;margin-top:2%; width: 100%">	
               
               <input type="checkbox" enabled  name="mo_sso_auto_create_admin" id="mo_sso_auto_create_admin" 
               ' . $this->escapeHtmlAttr($autoCreateAdmin) . ' value="true" /> Auto Create Admin users while SSO, if they do not exist.
                <br><br>
                   <input type="checkbox" enabled  name="mo_sso_auto_create_customer" id="mo_sso_auto_create_customer" 
                   ' . $this->escapeHtmlAttr($autoCreateCustomer) . ' value="true"/> Auto Create Customer while SSO, if they do not exist.
              </div>
              
       </td></tr>
       
       <tr>
       <td>
       <lable ><strong>User Auto Redirect Settings: </strong></lable>
       <div style="margin-left:17px;margin-top:2%; width: 100%">	
       
       <input type="checkbox" disabled  name="mo_saml_enable_login_redirect" value="true" 
             /> 
         Check this option to auto redirect users to IDP from login page (if not logged in).
        
      </div>
       </td>
       </tr>
       
       <tr>  <td><br>
       <input type="button" class="btn-round" name="link_setup" title="You can only make changes if you have configured your SP" 
       onclick="document.getElementById(\'signInSettings\').submit();" 
       value="Save" style="width:150px">
    </div>
 </td>
</tr>
</table>
</form>


            <br><br><br>
            <h3>DEBUG LOGS</h3>
            <hr>
            <form id="enable_debug_log" method="post" action=""> 
            <input name="form_key" type="hidden" value="' .$block->escapeHtmlAttr($block->getFormKey()).'" />
<input type="hidden" name="option" value="enable_debug_log" >
          
            <br>
            <input type="checkbox" name="debug_log_on" ' . $this->escapeHtmlAttr($enabledebuglog) . ' value="true" >Enable Debug Log

            <input type="button" class="btn-round" name="enable_debug_log"  onclick="document.getElementById(\'enable_debug_log\').submit();"     value="Submit" style="width:110px; margin-left:30px" >
            <br>
</form>
            <form id="clear_download_logs" method="post" action=""> 
            <input name="form_key" type="hidden" value="'. $block->escapeHtmlAttr($block->getFormKey()) .'" />
            <input type="hidden" name="option" value="clear_download_logs" >
            <p style="margin-top:20px;margin-left:10px">The error logs will cleared automatically on weekly basis. </p>
           
            <div style="text-align:left">
            <br>
            <input type="submit" class="btn-round" name="download_logs"  value="Download Logs" style="width:150px; margin-left:10px" >
            <input type="submit" class="btn-round" name="clear_logs"   value="Clear Logs" style="width:150px; margin-left:10px" >
            </div>
  
         </form>
      </div>
</div>
    ';
